---
layout: page
title: Using a Jumping Rivers Chromebook
output:
  md_document:
    variant: gfm
    preserve_yaml: true
editor_options: 
  chunk_output_type: console
---
```{r echo=FALSE}
source("R/functions.R")
```

Hey there! We're looking forward to having you at the next course. Chromebooks are simple to use, however they are a tad different to normal laptops. To get started using ours, please follow these instructions

1) Turn the Chromebook on. The power button is located on the top right of the keyboard.

2) Sign in as a guest. Please do not create any users. Guests are secure, as pages you view won't appear in the browser history and they won't leaves other traces like cookies on the computer, after you have signed out. Note that this also means file you download and bookmarks you create __*will not*__ be preserved upon signing out/closing down.

3) Connect to your WiFi. This can be found in the bottom right of your screen, along with brightness and sound. Note you'll have to reconnect to your WiFi each time you sign in. 

4) Sign in to your e-mail and complete the pre-course typeform sent to you by your trainer.

That's it! If you have any problems get in touch with theo@jumpingrivers.com and we'll get back to you ASAP. 