---
layout: page
title: Installing Python
output:
  md_document:
    variant: gfm
    preserve_yaml: true
---
```{r echo=FALSE}
source("R/functions.R")
```

For this course you must all have the [Anaconda distribution](https://www.anaconda.com/download/) of Python and on top of that you must download the course modules we have built. Instructions to do so are as follows

## Anaconda: 

1. Go to [https://www.anaconda.com/download/](https://www.anaconda.com/download/)

2. Click download Python 3.7

3. Run the installer (Make sure during the installer you tick the box that says add anaconda to my PATH environment variable. You may need administrative rights for this)

4. Open Anaconda Navigator 

5. Choose the integrated development enviroment (IDE) you'd like to code Python in and install it. I will be using Spyder for the course as it is much better for teaching purposes but it is totally up to you what you use. Another popular choice is jupyter notebooks. 

6. Run the lines of code:

`import numpy`
`import pandas`

If you don't get any errors Python has been properly installed.

## Installing course packages:

1. On whatever operating system you are on open the command line. Beneath are some clues as to where you might find these

  * Mac -  Terminal application 
  * Windows - Search for the Command prompt 
  * Linux - Terminal

2. In the command line, run the lines of code:

`pip install jrpyintroduction`
`pip install jrpyprogramming` 

3. Open your IDE of choice and run the lines of code:

`import jrpyintroduction`
`import jrpyprogramming` 
