---
layout: page
title: What makes a suitable Room
output:
  md_document:
    variant: gfm
    preserve_yaml: true
editor_options: 
  chunk_output_type: console
---

There's a couple of thing we need within a room for you to get the best out of us when training:


1. WiFi! The trainer and all attendees must have access to WiFi. 

1. It must have a reasonably sized screen. Having a 50" tv for a team of 5 might be ok, but for a team of 20 it is inadequate. A projector is normally best. 

1. Power supplies. There needs to be an adequate number of sockets for everyone's chargers (Yes, it's happened before!).

1. There must be a HDMI port for our laptops to plug in to, otherwise we can't show you our beautiful presentation. 

1. There needs to be enough seating for everyone and the room must be a decent shape. No conference tables as the people at the back have a very tough time seeing. 

1. We like to have plenty of coffee/water breaks. There needs to be a good place to restock on said things, i.e. A kitchen, cafe etc. 

1. There has to be temperature control of some sort. Having 10 people, their laptops and their laptop chargers in a room all day can get quite, erm, sweaty. 

Thanks for complying, this will benefit you more than us. Look forward to seeing you at the course! 